sudo: required
language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: "NmbaUJ9wn1FfTz5zsJxbbzT6ec1e1Ry/DdyXl3mqxdh04PL3BlrPAa4vSw12lfmXpPgQxpLIMvbsW7H2M67S/knHeAFpb5N/JMVzvfvgYATg9sFZKjU2fl2URI8eawqazjdPYErbgJHV6mO1d5NaixdILxJLXxIPe4huGFlht9xbHj8xQqfqUyaQTFJdKVVrX0ndx8xJoQsnJrKuT9evQKmv2i2ek4j02wbZW10iKVYWE42A0Dwv72qRuiUXeg81kkacAFXqKM7ff31CEkiYtc2Y4sNIjRqRJ+5UAkffWi0d9B2sT8p5nMA01eZ/os5SzNJEl6u6v/HOO7Sca/THVcciAf65IMG74/5vX5cYGBLcgENpr7PeRQWZ7JyA4tTYnY9nu6uW9r9BC2XWp/EG2I/TJN5mBdYcGU6XClSUIHImP4gTUsKvgmZFNk916ZfojXdbP3fdRhnIYHVpy2J99g3ugt8fslgnpthrYTHRMnRg2C0UPzNRf+RWYRdw5gjtYh+5oH97hrq4Njqm9/KzPDD87z/bXxu+6BlonOs8LiR0HchMRXYcOJWcxCcM4EuCdcTJHltuCDLfWmtpUIJ3QUjkSpf0CrB8nXpleiu8uASMbSgPYk1hvQOuGy4S9fy6Y6QeGX2bTcKoOIbSW22X6Yd5+7g5see/x70qWNv1GwU="
  - secure: "GVJ0uaDcs0RqdtIMbPtG0m5LlG9h4LfS3Y5oiPZ/BqELvtEHGDVrkLcLOazQSPv98/6o79qnekxWQhL9h3yRn3aFyTOVOZlbHNOzqhM66UJuGlbifiK6G1HDLfAPq9Xj0R2bgmdr5A43bvkDVzsqHf3LVXy32ncziDDk6KaIznDuoWHimU9GZUNIp1a7I3uUbbaAwhMTMNfKA0e4w1wQnlgCtMdDGHzFUbh+PEdn0wjeNQzHi1BryPES3jsc4W4L5EjDy2zRnp4KewVbL1e13O2EM0jOavjVvQRdpkMdc+b4iTW6nX2pW5xRGgYqlW0n/nU7n6pNsnuFpWKdHM4ALedTPm6YRd7fEGutUjU7u23BTrFlpyWIgQRz7VZYWb+VwACNDZ9eAnBpbkueGUr42hdQsvLfGbIJZRwDTVp/+WnMxMv1I+SmMLvZSas/1EvlkUUzjll/6onRx3Vj2qdadNLfR9GbYOKEqnmgVhxkMjwleW4g35a3vLugbHBZSRBlGDFsQ+Mbzl1wm6ZW2tJNuzGQ2rHxnGqjh8bH5KsRmyuHrhBCaMsG45LAl0wne7zY+gshwK3HLXcsVCy+FX87fXt6A4Uc0a2wTV+vuP0JUt9hbKJ/7VJZS6MlRoxxLKUGrYI7Fr7M+Yt+5QrTJ8Q1m5DMeQ7O+xZ0ji0DVH4xuFo="
  - secure: "C9dcpnl/In245gmPw7Gr+f2+BvvPgqHG3ey4LsBuuV/k9RQ0swR6cG65lrf23yUmGdZ3jcRPQT3Aot+4+4INiXoSPPbuyld6Al3VC1JFblPZZIEPK8aKMxSutedC9UldJBFtXmX3rYZDuO67SFWO58FcxEhvAeK+rbkT1Vv/cCEpsrKvD3Jx25nulJ7kLGVNg5I2Sfec7bYl/alPHoe4R9T419nSaWgrcNW+p965eHF2FCdiQkfajAQTULacaLuWdU0In4vKV8O8kJdYoDwer0QnLdv5ZpsjSzf/9ww2eWKBTyveTKEebbdAyCxlu4SmjBSXvvptHkVUiyq8yDa0c+QQxT8UlwuGP/tPRetQr2zfpbzZyOc9vaRPNDeJ/UR9knSwOMjsMlSlg/ttCljDEVZnh3o2D24BPj29mVp+JGDRy0DHNMmP/UF1+EHifg4e7lMibAEshyx3QGmn27Q98h4Bgh1G3TD19Con2LT7f+ksEQQ0I3GhEwGaFry7K/c5IHGw5/05Y/J1+DB4cSLM8SQB7QQ6uqZRmNqqb7wD+VPB/e0crEjnFeQoi2RvPJXo8BMJAbeL3WGBmhINcI4ohkWX39DSTD7nbn8tkktlp4oL6j43dFymmKhwZR5iiceAUnNfPy6q4JI3zpz3WcZaau815U2thmTCI0SEOrQlz6I="
  - secure: "MPFqZpG+Iiazba6DzPb+Cp97kPjK2YcwnLJyv/w3AUzuHyYqdmwG8CsgifkVY32p9q8TmkGv/Y/HmLcaowsvGzCDkZYDfRkMDpMDTigxmDWUgaO6xx1/EDppbewGfhN5+90Fj1q+7Bm3dYA8qszCa+iW0ZL7iO4aGtdN+cqgKrHWgeWxOa1gxigk6NtWh8MfKX7q4OXdPAYwEllwohinPKdNF7eSX5oC82DKWdgqpkDHjG+oFwwx46rmwp1Gl7wPgLqDkkIHnT0WYc1p65RUGMFWGKUJWomxiWfA/huDVE8vQL8B1ObMeVGSZ/yOPYeFhRWWnf0JG6fdSX1yklHU1k7i1x0fUnFHOe/0miHhRkm554iKkfD1wiVTYuj+/rhKU7qJzHExmuild+q7JNibk344BPrbeQJfy4nnu6yWA57AHXjsxqYELHrIbU4qib/bZqJnQnmrIOHHTlvhLi3L+vO4QMQIiKBzCcewcTsuEgQjQUspqDYm/+zPQz6b1VlbgyoDisbRF/ZJeEtUcttMtBBCH/n+K5RYaeeMXNY9qxM+tvHJwGpl0Sh2wDoupppezBsTimr6GqZ22lav4eP5seZpJQmyOogx/P8mdfljNcd1DAKQRv6uJpd605f1WHyLZq5xWd0aThvHA6n/7Rlwk8BEaDMNOo2pviLqPUSUAXU="
  - secure: "FG3IjnY9zOVSLr+9XjA2nbEODcjqTjw/OTWg1EjHoZiW4q12gGmz3lOvaYNYeYPzndS3hBWqfcVV/hSdyxF3I8UrLWqYFmREaUWj+n5TE6jsPkBtTTgpplOdJtryihvDz6MU3VqUtdJh1d2/jRMHSDriKzW8MR5eNf2tErEb6qtPK8a4NQOmbN5dDOmTFqTD5cMEbOjLx+CUpQMmjaVVJU2ZgZaZUSws9Z/yh583XoQODmxtiLpK6t2XUBzte4mTkaX55lD7jHKiGrd+HV5/KDg9b+U6Rvxo3Enw/azZx1JzRdaIvpwVqFWvQikUZXZx+foIWVos4bnao/s0rs3QLq1DqPTXw+fR22yiIhEr8VWrou+oiUVuhVjvZn4MoujSkWnyQ65QocjSnnOeExLZruDM2tKePZIyIU+67MOYzDiqiNUQj9VV4jqeCvxzvmaL4duUbQNkXjNbu5P7EEcoXhki3yjCjzwTABRyFRw0lufyZ40XEaIIj8XFgxiRrZclUM/HCVLN3ZhbTWTONQS9vvpPajhZD8xaItsFqBF+sSbZE8iK6JXzto0t/MHXqSw+z1tp04bLmbuuTgtYCNXmRZb2X1x3bmvGVrOA2s8QSRDzwNUsiubaqvrZZY1MzuW8H7JruJEJD0Zx3Zd1sf9U2DaIcqL7yXvyfzTkpB3gN3c="
  - COMMIT=${TRAVIS_COMMIT::7}

git:
  depth: 500

addons:
  sonarcloud:
    organization: "sam-kaz-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=sydkaz/freelancer-kit
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: freelancer-kit-syed
