sudo: required
language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: "iNOos4kSEc9/qAdRUawve5Zv89hPNBJkRhw/HVNj12CT3HsoetWEwHK3Psm1ryXoHq+fh3CIK/aCKeq8moXd0FPBtrwd0PSva6OJGoH+Gk50bkiw5hi0u8Hm55lm//Ji+8Spz/W+psT+MMRkAOLIu2rnnc+izUYJEXRbmXefA1bd9bSk1+POfuLTk76peg1VTrzFKJ2vy80brAOXMHym8hqa6iSDDdBeXv8GAXjUzbZnFfZ+v5eAlZluR2Xt4aV8E+69O00RoCjtHmoYEHBOkV7PueMBObbJo73n9m2fhtXbPr7/rTQ5bKvTvVxgVDdBtQfeh41OCmb2Lbe4wnt3Y78fX4+B5eIdgJSi2MzJ2qQDcpatluBe4Akf3Gar+rxK7WoDEgVu/5HBtytLQLMkQLMAnIs/nR6XhXku5P4DKhPwhEyww51AiQtRcoMhWgEefDEo+iRGyOfLd2gF8FSr+8sKHMH6vFQ6B3Bn2OKA3IC/sgNp0qrUW2hdlg+sBFnFog1SZsar4/RYnpXzgwdk9clnVNrADZnc/c2qGt4jMw4SjVoBYif1jDSy2JVxklTY7333509g07gadcU4C8oDXJKQgSlzxUpI7WhvYJIzDGK1VO8Q/RebCH8N41YugXoW10/b/tL9CymfFt3+iFF+6C8Seme9MUDAh1NfR1JtYC4="
  - secure: "jAQQb1iQArMe+Bo7tdDg8QRZVOyec4xwcby9lQkTGrhVpT7BGEUx7iMbNVb1XR2E3R/og5eawI6DKKW9M90iFWMSYCdfRxNcYxmb2qW2kaj2vP5ri83dSJtYpKHeJf2yO0PttvZRapC57Z1sIWrs04om4nZ+otjPnNhXhz0i3eJWeqLhvDQV4Upu5pwMhkKU+tihwh3c2doM0ww9XGe4ZQLH12KDRSJTMby13VSXlYhsJR3h5cnK4yR6A7xebs6Zph4KDz5ITF62zArvgHv9enf+e2RSCljPnljxJin/qy4zLrkEdgqzQfVJSPbQjkUHJqjhPNth0o7m1A0pzng5sjm3UTFfdrK0h+DXu9zaVuHkVfS2dWZ7PwWC1YMOG3mXlpiuMJsTrpMfmxrbga7KiPBsRae81byC0GCbwiOAc5GVoNUHNBR92Fw9LERQatltIJkuo+XHB4EZdbgq8hWZX7nrpPFTs479j1t8zrQP0E6neGc//q74cvKusVzw9Ov+sjrA/65gsVrtN7FKxViBlMWWyP5AYAULjguptmvD8HdBxUuJ33cuze+PKCyXWmYUvY+PgQq8D18SBS0U2s/ZqVnxhrWKlbQ1aLF0sHu/j5FOovOiFzuJDGSMOQYl1eSLK3tTUNXLAoHvsWcwMfqKaDtgUqJEJyvCrfE6tDLPGEA="
  - secure: "lbXmIOcqMHHjVOFY2WHomv7GiIGpRHV/0BnjpQHJJUAF+tsPU9DX7xwaPQpH3Gftbua5bK0nNI9WtrnxAC+eaxrJAgveKMNza99dRr7BiHQNQGE4MtZNd/Lf9CVhuM9RX1X21K9fWncASC+Bi7Yb/OGxx/64yzWWawhyAlK3oyGZXkqeX/O1THDtJkmh6GxsqOcRAH3SLfIA0yc9HoUSueUe0i23q4SI9R2MURot5S/BwgtnyYLBll09UakrTcwW9ytkeCyfJbW3At+/1cy2KhO3021+/uLBV85Bl2wgdMd75FP5VauxElPrYqwQVqkSdD6IXmSoyeOyl1T7QHc4wbcJCP/5rYwPesIrR4ugCzX1yvPV8qoW+j62IEiCMrDfjPHIYHRZAqQKx27lhOnIhsHVY4punAZvVTvsdD/vd5tHCvqjqGnQrttuoD6075ZTAsaGmQHJe+P4OWU3C14ws1IWU6X8W3qZ97h4gWSInqZnxal4OJqc2OkalPwVJt/LKLBVyLOZ62uQrmIjW8sB4J8xRb22skxm8T98QJJ+64UVI/nPauMpMqO/AFSKc7eHDbrqmJaPbfIdm+HnG0j58LvzkMMmlb2SVHkEB4hVb8UF9F6K2+/7kC9X6JZTC+58K5tDa1GXKWujnUShWEUI29tSmf8F1x6pW82ARKyR++o="
  - secure: "Yh9ANvbTEI3823EHVRgM9q697sKvKixRVeAMcJCWZqSiz8bNUuPWW7WHxNSz88cSkvfSKUMAbeSCsqepZH4inElbdgELNn8K5N7vHTXfmpYabGE4C7WxDCpQ0K2U+iL8uqY3xElm202bSSTl+KZIlsnCJKY8dwHsbv/CREBW1Uu+yA/Gs4khtrtDjn7ZEAfpKhHeoVl4P8cpyti7yQa28j/nkYZIHcwWgb6Pllln6KUpxegOy3jOsxNRw0AQ9GMWVVqJUc8wQ2sgTHTJgbnUdmZ6YJkjm/GPwA4VPjrbeLnncmePfH4OJYsTV2nWauYzs3LPRwtgbkpQa9Qsr0HwPJpn/7jrYkKu9XGn3pfvH+T78aGIujhKJ+96QwGl9oKVTOjs9ZXAZan5RqXG/LxH/ZsIAvFZ6okTlFteqmnzOi1PE6QTFqzXEKtkYKnXmZX/2Y/AGLv1Z5Ts8zDLy9AcWR08l0ikCjB+LO/WiagYjRsX+udmlK4WRgjHKD0GLH1EtgApTCCn8Eq8vNeRG/45EFlpm8/qpFZ9+dmHJOWIvCJt2UCTj+AMsUDt0/hpK846hy7BHnYTUatpzy9qYYIyR3TaCOH2SOWw5L734MowucFZ2a6gagYtQz9H/YFWenWrVb1InjcyibIM94RDyXAl1XHQVz3WziqYPmzyU7+JGk4="
  - COMMIT=${TRAVIS_COMMIT::7}

git:
  depth: 500

addons:
  sonarcloud:
    organization: "travis-organisation"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=sydkaz/freelancer-kit
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY

